# Generated by Django 5.1.5 on 2025-02-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_category_notes_user_notes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
